#!/usr/bin/env node
/* Bakes <title>, description, canonical, favicon and social-card tags
   into every page's <head>, using assets/topics.js as the source.

       node tools/sync-meta.js          # write
       node tools/sync-meta.js --check  # exit 1 if anything is stale (CI)

   Why a build step and not JS injection: Twitter, LinkedIn, Slack and
   Facebook crawlers do not execute JavaScript, so these tags have to be
   present in the served HTML. Everything between the meta:start and
   meta:end markers is generated - edit assets/topics.js instead. */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CHECK = process.argv.includes("--check");

global.window = {};
require(path.join(ROOT, "assets", "topics.js"));
const { TOPICS, SITE } = global.window;

const START = "<!-- meta:start (generated by tools/sync-meta.js — edit assets/topics.js) -->";
const END = "<!-- meta:end -->";

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
           .replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function block({ title, desc, url, image, type }) {
  const lines = [
    `<meta name="description" content="${esc(desc)}">`,
    `<link rel="canonical" href="${esc(url)}">`,
    `<link rel="icon" type="image/svg+xml" href="assets/favicon.svg">`,
    `<meta name="theme-color" content="#faf6ef">`,
    `<meta property="og:type" content="${type}">`,
    `<meta property="og:site_name" content="${esc(SITE.name)}">`,
    `<meta property="og:title" content="${esc(title)}">`,
    `<meta property="og:description" content="${esc(desc)}">`,
    `<meta property="og:url" content="${esc(url)}">`,
  ];
  if (image) {
    lines.push(
      `<meta property="og:image" content="${esc(image)}">`,
      `<meta property="og:image:width" content="1200">`,
      `<meta property="og:image:height" content="630">`,
      `<meta property="og:image:alt" content="${esc(title)}">`,
      // Twitter falls back to the og: tags for everything but the card type.
      `<meta name="twitter:card" content="summary_large_image">`
    );
  } else {
    lines.push(`<meta name="twitter:card" content="summary">`);
  }
  return [START, ...lines, END].join("\n");
}

const ogFor = (slug) => {
  const rel = path.join("assets", "og", slug + ".png");
  return fs.existsSync(path.join(ROOT, rel))
    ? `${SITE.base}/${rel.split(path.sep).join("/")}`
    : null; // no card rendered yet - omit rather than point at a 404
};

const pages = [
  {
    file: "index.html",
    title: SITE.name,
    desc: SITE.tagline,
    url: SITE.base + "/",
    image: ogFor("index"),
    type: "website",
  },
  ...TOPICS.map((t) => ({
    file: t.slug + ".html",
    title: `Day ${t.day} · ${t.title}`,
    desc: t.blurb,
    url: `${SITE.base}/${t.slug}.html`,
    image: ogFor(t.slug),
    type: "article",
  })),
];

let changed = 0;
const stale = [];

for (const p of pages) {
  const abs = path.join(ROOT, p.file);
  if (!fs.existsSync(abs)) {
    console.error(`  MISSING  ${p.file} (listed in topics.js)`);
    process.exitCode = 1;
    continue;
  }
  const before = fs.readFileSync(abs, "utf8");
  let after = before;

  // 1. normalise <title> so the tab, og:title and the index all agree
  const wantTitle = `<title>${esc(p.title)}</title>`;
  if (!/<title>[\s\S]*?<\/title>/.test(after)) {
    console.error(`  NO <title>  ${p.file} - skipped`);
    continue;
  }
  after = after.replace(/<title>[\s\S]*?<\/title>/, wantTitle);

  // 2. preconnect to the font *file* host - the googleapis preconnect
  //    only covers the stylesheet, and the woff2s come from gstatic.
  const GSTATIC = '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
  if (!after.includes("fonts.gstatic.com")) {
    const gapi = after.match(/[ \t]*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com"[^>]*>\n?/);
    if (gapi) {
      after = after.replace(gapi[0], gapi[0].replace(/\n?$/, "\n") + GSTATIC + "\n");
    } else {
      console.error(`  NO font preconnect  ${p.file} - gstatic hint not added`);
    }
  }

  // 3. keep nav.css immediately after base.css, so a page's own inline
  //    <style> always wins over both instead of only over base.css.
  const baseLink = after.match(/([ \t]*)<link rel="stylesheet" href="assets\/base\.css">\n?/);
  const navLink = after.match(/[ \t]*<link rel="stylesheet" href="assets\/nav\.css">\n?/);
  if (baseLink && navLink) {
    after = after.replace(navLink[0], "");
    const fresh = after.match(/([ \t]*)<link rel="stylesheet" href="assets\/base\.css">\n?/);
    after = after.replace(
      fresh[0],
      fresh[0].replace(/\n?$/, "\n") +
        fresh[1] + '<link rel="stylesheet" href="assets/nav.css">' + "\n"
    );
  }

  // 4. replace the generated block, or insert it after the viewport meta
  const gen = block(p);
  if (after.includes(START) && after.includes(END)) {
    after = after.replace(
      new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "[\\s\\S]*?" + END),
      gen
    );
  } else {
    const vp = after.match(/<meta name="viewport"[^>]*>\n?/);
    if (!vp) {
      console.error(`  NO viewport meta  ${p.file} - skipped`);
      continue;
    }
    after = after.replace(vp[0], vp[0].replace(/\n?$/, "\n") + gen + "\n");
  }

  if (after !== before) {
    changed++;
    stale.push(p.file);
    if (!CHECK) fs.writeFileSync(abs, after);
  }
}

if (CHECK) {
  if (changed) {
    console.error(`Stale metadata in ${changed} file(s):\n  ` + stale.join("\n  "));
    console.error("Run: node tools/sync-meta.js");
    process.exit(1);
  }
  console.log(`All ${pages.length} pages have up-to-date metadata.`);
} else {
  console.log(
    changed
      ? `Updated ${changed} of ${pages.length} pages:\n  ` + stale.join("\n  ")
      : `All ${pages.length} pages already up to date.`
  );
}
